version: '3.9'

services:
  frontend:
    build:
      context: ../
      dockerfile: front-end/Dockerfile
    container_name: teddy-frontend-isolated
    ports:
      - '4200:80'
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:3000/api/v1}
    # Assume que o backend já está rodando
    networks:
      - teddy-network
    restart: unless-stopped

networks:
  teddy-network:
    external: true
