version: '3.9'

services:
  backend:
    build:
      context: ../
      dockerfile: back-end/Dockerfile
    container_name: teddy-backend-isolated
    ports:
      - '3000:3000'
    env_file:
      - .env
    # Assume que a infra global (postgres) já está rodando
    networks:
      - teddy-network
    restart: unless-stopped

networks:
  teddy-network:
    external: true
